### ISSUE TITLE
Add border to popovers

### ISSUE THREAD

**Issue by shawnlehner** [Burkson/ridestyler.ui#8]
The stail on the popovers looks odd being the only orange thing. Can we add a border on the side of the popover that corresponds to the stail? See screenshot below for example.

![image](https://user-images.githubusercontent.com/5307103/73018888-52860800-3dd7-11ea-8fbc-4c7611a8bdc0.png)

**Comment by bbless97** [comment]
Added border to all popovers:
![image](https://user-images.githubusercontent.com/47756879/73570589-7bcf1580-4421-11ea-9a0a-2e1bce521ae1.png)

**Comment by bbless97** [comment]
Added border to all popovers:
![image](https://user-images.githubusercontent.com/47756879/73572170-fe0d0900-4424-11ea-8a6d-d56552e716da.png)

**Comment by bbless97** [comment]
The change to the portal is live on alpha

**Comment by bcarasco** [comment]
For reference: commit 4ec58e0640ea8f5f1515f4e6a1782dc1ea7c8394
